name: p24_sdk
description: Przelewy24 Mobile Payments SDK integration Flutter integration for iOS and Android
version: 1.0.55
homepage: https://github.com/przelewy24/p24-mobile-lib-flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: pl.przelewy24.p24_sdk
        pluginClass: P24SdkPlugin
      ios:
        pluginClass: P24SdkPlugin
